In [25]:
import sys

import pandas as pd

print(sys.version)

3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]

In [26]:
df = pd.read_excel('./first_quote_data.xlsx', index_col=False)

df

,카테고리,한글,원문,발언자,출처,Unnamed: 5
0,지식,모든 인간은 선천적으로 지식을 희구한다.,All men by nature desire knowledge,아리스토텔레스,NaN,Aristotle
1,NaN,쓸데 없는 지식에서도 큰 기쁨을 얻을 수 있다.,There is much pleasure to be gained from usele...,버트런드 러셀,NaN,Bertrand Arthur William Russell
2,NaN,아는 것이 힘이다.,Knowledge is power.,프랜시스 베이컨,NaN,Francis Bacon
3,NaN,지식에 대한 투자는 항상 최고의 이자를 지불한다.,An investment in knowledge always pays the bes...,벤자민 프랭클린,NaN,Benjamin Franklin
4,NaN,의지와 지성은 동일하다.,Will and intellect are one and the same thing.,바뤼희 스피노자,NaN,Baruch Spinoza
...,...,...,...,...,...,...
95,NaN,전쟁은 모두 도둑질만을 목적으로 삼는다.,NaN,볼테르,NaN,Voltaire
96,NaN,백번 싸워 백번 이기는 것은 최선 중의 최선이 아니고 싸우지 않고 적을 굴복시키는 ...,NaN,손무,손자병법,孫武
97,NaN,"무기는 설사 백 년 동안 쓸 일이 없다 해도, 단 하루도 갖추지 않을 수 없다.",NaN,다산 정약용,NaN,NaN
98,NaN,"천하가 비록 편안하더라도, 전쟁을 잊으면 반드시 위태로워진다.",NaN,사마양저,NaN,司馬穰苴
99,NaN,전쟁을 좋아하는 민족은 반드시 망한다. 그러나 전쟁을 잊은 나라 또한 망한다.,NaN,리델 하트,NaN,Sir Basil Henry Liddell Hart

목표 데이터 형식

meta_quote_id, ko_sentence, org_sentence, quote_source, || speaker_id, speaker_name, speaker_org_name

meta_quote_id는 항목마다 새로 생성,

speaker_id는 dict에 name, org_name이랑 같이 넣어서 중복 찾기

In [27]:
sen_columns = ['meta_quote_id', 'ko_sentence', 'org_sentence', 'quote_source', 'speaker_id']
speaker_columns = ['speaker_id', 'speaker_name', 'speaker_org_name']

sentence_table = pd.DataFrame(columns=sen_columns)
speaker_table = pd.DataFrame(columns=speaker_columns)

print(sentence_table[:1], speaker_table[:1])

Empty DataFrame
Columns: [meta_quote_id, ko_sentence, org_sentence, quote_source, speaker_id]
Index: [] Empty DataFrame
Columns: [speaker_id, speaker_name, speaker_org_name]
Index: []

In [28]:
df[:10]

,카테고리,한글,원문,발언자,출처,Unnamed: 5
0,지식,모든 인간은 선천적으로 지식을 희구한다.,All men by nature desire knowledge,아리스토텔레스,NaN,Aristotle
1,NaN,쓸데 없는 지식에서도 큰 기쁨을 얻을 수 있다.,There is much pleasure to be gained from usele...,버트런드 러셀,NaN,Bertrand Arthur William Russell
2,NaN,아는 것이 힘이다.,Knowledge is power.,프랜시스 베이컨,NaN,Francis Bacon
3,NaN,지식에 대한 투자는 항상 최고의 이자를 지불한다.,An investment in knowledge always pays the bes...,벤자민 프랭클린,NaN,Benjamin Franklin
4,NaN,의지와 지성은 동일하다.,Will and intellect are one and the same thing.,바뤼희 스피노자,NaN,Baruch Spinoza
5,NaN,유일한 선은 지식이고 유일한 악은 무지다.,The only good is knowledge and the only evil i...,소크라테스,NaN,Socrates
6,NaN,지식과 목재는 잘 다듬어지기 전까지 많이 사용해선 안 된다.,Knowledge and timber shouldn't be much used ti...,올리버 웬들홈즈,NaN,Oliver Wendell Holme
7,NaN,지적재산권의 유통기한은 바나나만큼이나 짧다.,Intellectual property has the shelf life of a ...,빌 게이츠,NaN,William Henry Gates III
8,NaN,모든 지식의 확장은 의식적 행동을 무의식으로 만들 때 발생한다.,Every extension of knowledge arises from makin...,프레드리히 니체,NaN,Friedrich Wilhelm Nietzsche
9,NaN,무지를 아는 것이 곧 앎의 시작이다.,True knowledge exists in knowing that you know...,소크라테스,NaN,Socrates

In [49]:
sen_columns = ['meta_quote_id', 'quote_category', 'ko_sentence', 'org_sentence', 'quote_source', 'speaker_id']
speaker_columns = ['speaker_id', 'speaker_name', 'speaker_org_name']

sentence_table = pd.DataFrame(columns=sen_columns)
speaker_table = pd.DataFrame(columns=speaker_columns)

speaker_dict = {'speaker_name' : 'id'}

category = ''
speaker_id = 1

for i in range(len(df)):
    new_sentence = {}
    dlist = df.iloc[i, :]
    cate, ko_sen, org_sen, speaker_name, quote_source,speaker_org_name = dlist[:6]
    category = cate if type(cate) == str else category
    
    if type(ko_sen) == float:
        continue
    
    if speaker_name not in speaker_dict:
        speaker_dict[speaker_name] = speaker_id
        new_speaker = {'speaker_id':speaker_id, 'speaker_org_name': speaker_org_name, 'speaker_name' : speaker_name}
        speaker_table.loc[speaker_id] = new_speaker
        new_sentence['speaker_id'] = speaker_id
        speaker_id += 1
    else:
        new_sentence['speaker_id'] = speaker_dict[speaker_name]
    
    new_sentence.update({'quote_category': category, 'meta_quote_id':i+1, 'ko_sentence': ko_sen, 'org_sentence': org_sen, 'quote_source': quote_source})
    sentence_table.loc[i] = new_sentence

sentence_table = sentence_table.where(pd.notna(sentence_table), None)

In [51]:
for i in range(len(uni_category := sentence_table.iloc[:, 1].unique())):
    
    sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1

/tmp/ipykernel_15432/145910735.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1
/tmp/ipykernel_15432/145910735.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1
/tmp/ipykernel_15432/145910735.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1
/tmp/ipykernel_15432/145910735.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1
/tmp/ipykernel_15432/145910735.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1
/tmp/ipykernel_15432/145910735.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1
/tmp/ipykernel_15432/145910735.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1
/tmp/ipykernel_15432/145910735.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1
/tmp/ipykernel_15432/145910735.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1
/tmp/ipykernel_15432/145910735.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1
/tmp/ipykernel_15432/145910735.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1
/tmp/ipykernel_15432/145910735.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1
/tmp/ipykernel_15432/145910735.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1
/tmp/ipykernel_15432/145910735.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1
/tmp/ipykernel_15432/145910735.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1
/tmp/ipykernel_15432/145910735.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1
/tmp/ipykernel_15432/145910735.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1
/tmp/ipykernel_15432/145910735.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1
/tmp/ipykernel_15432/145910735.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1
/tmp/ipykernel_15432/145910735.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sentence_table.iloc[:, 1][sentence_table['quote_category'] == uni_category[i]] = i+1

In [80]:
quote_meta = pd.DataFrame(columns=['quote_id', 'quote_category_id', 'quote_subtext_id', 'quote_speaker_id', 'quote_source'], dtype=int)
speaker = pd.DataFrame(columns=['speaker_id', 'speaker_name', 'speaker_org_name', 'speaker_summary'])

quote_sentence = pd.DataFrame(columns=['sentence_id', 'ko_sentence', 'org_sentence'])

In [81]:
for i in range(len(sentence_table)):
    quote_id, category, ko_sen, org_sen, source, speaker_id = sentence_table.iloc[i, :]
    quote_sentence.loc[i, :] = {'sentence_id':quote_id, 'ko_sentence': ko_sen, 'org_sentence': org_sen}
    quote_meta.loc[i, :] = {'quote_id':quote_id, 'quote_category_id': category, 'quote_speaker_id': speaker_id, 'quote_source':source}

/tmp/ipykernel_15432/2601280635.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '러브액츄얼리' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  quote_meta.loc[i, :] = {'quote_id':quote_id, 'quote_category_id': category, 'quote_speaker_id': speaker_id, 'quote_source':source}

In [82]:
for i in range(1, len(speaker_table)+1):
    speaker_id, speaker_name, speaker_org_name = speaker_table.loc[i, :]
    speaker.loc[i, :] = {'speaker_id':speaker_id, 'speaker_name':speaker_name, 'speaker_org_name': speaker_org_name, 'speaker_summary':None}

In [86]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:inmo1245@54.180.66.132:3306/31quote')

In [89]:
# speaker.to_sql('speaker', con=engine, if_exists='replace', index=False)
# quote_meta.to_sql('quote_meta', con=engine, if_exists='replace', index=False)
quote_sentence.to_sql('quote_sentence', con=engine, if_exists='replace', index=False)

92